### ISSUE TITLE
[Enhancement/功能请求] 希望生物清理是让生物消失，而非被杀

### ISSUE THREAD

**Issue by Star-Jirachi** [Nova-Committee/Atom-Sweep#10]
### Checks/检查

- [X] I confirm that I have [searched for existing issues / pull requests](https://github.com/cnlimiter/Atom-Sweep/issues?q=) before reporting to avoid duplicate reporting./我确认在报告之前我已经搜索了[现有的问题或者拉取请求](https://github.com/cnlimiter/McBot/issues?q=)，以避免重复报告。
- [X] I confirm that I noted that if I don't follow the instructions, the issue may be closed directly./我确认我已经检查，如果我不按照说明进行操作，该问题可能会被直接关闭。

### Description/描述

mod清理生物时，是将生物杀死。被mod杀死的生物不会掉落经验。但是会正常掉落物品。
因此服务器有玩家利用这个机制刷取物品。
希望能出个功能，生物清理是直接让生物消失，而非被杀。

**Comment by cnlimiter** [comment]
可以使用最新构建的
