### ISSUE TITLE
[Enhancement/功能请求] 本mod的白名单功能可否支持通配符功能？

### ISSUE THREAD

**Issue by ETA0101** [Nova-Committee/Atom-Sweep#12]
### Checks/检查

- [X] I confirm that I have [searched for existing issues / pull requests](https://github.com/cnlimiter/Atom-Sweep/issues?q=) before reporting to avoid duplicate reporting./我确认在报告之前我已经搜索了[现有的问题或者拉取请求](https://github.com/cnlimiter/McBot/issues?q=)，以避免重复报告。
- [X] I confirm that I noted that if I don't follow the instructions, the issue may be closed directly./我确认我已经检查，如果我不按照说明进行操作，该问题可能会被直接关闭。

### Description/描述

举例：如果我想让本mod不清扫老鼠模组中的所有生物，可否在白名单内添加“rats:*”来实现此项功能？

**Comment by cnlimiter** [comment]
> ### Checks/检查
> * [x]  I confirm that I have [searched for existing issues / pull requests](https://github.com/cnlimiter/Atom-Sweep/issues?q=) before reporting to avoid duplicate reporting./我确认在报告之前我已经搜索了[现有的问题或者拉取请求](https://github.com/cnlimiter/McBot/issues?q=)，以避免重复报告。
> * [x]  I confirm that I noted that if I don't follow the instructions, the issue may be closed directly./我确认我已经检查，如果我不按照说明进行操作，该问题可能会被直接关闭。
> 
> ### Description/描述
> 举例：如果我想让本mod不清扫老鼠模组中的所有生物，可否在白名单内添加“rats:*”来实现此项功能？

试试最新的构建版本

**Comment by cnlimiter** [comment]
已支持
