### ISSUE TITLE
[Bug/漏洞] 用的是破晓之界2.7的服务端

### ISSUE THREAD

**Issue by fengyoun** [Nova-Committee/Atom-Sweep#14]
### Checks / 检查

- [X] I confirm that I have [searched for existing issues / pull requests](https://github.com/cnlimiter/Atom-Sweep/issues?q=) before reporting to avoid duplicate reporting./我确认在报告之前我已经搜索了[现有的问题或者拉取请求](https://github.com/cnlimiter/McBot/issues?q=)，以避免重复报告。
- [X] I confirm that I followed the Docs and read the [Changelog](https://github.com/cnlimiter/Atom-Sweep/releases/latest), but this problem still exists./我确认我按照文档配置并阅读了[Changelog](https://github.com/cnlimiter/McBot/releases/latest)，但这个问题仍然存在。
- [X] I confirm that I noted that if I don't follow the instructions, the issue may be closed directly./我确认我已经检查，如果我不按照说明进行操作，该问题可能会被直接关闭。

### Java Version / Java版本

17

### Minecraft Version / Minecraft版本

1.18.2

### McBot Version / Atom-Sweep版本

0.2.0

### Description / 描述

加上该mod之后使用stop会卡住很久，去掉该mod又能正常stop，

### To Reproduce / 重现

stop

### Log / 日志

[2024-05-13-2.log.gz](https://github.com/Nova-Committee/Atom-Sweep/files/15289953/2024-05-13-2.log.gz)
[latest.log](https://github.com/Nova-Committee/Atom-Sweep/files/15289954/latest.log)

**Comment by 3944Realms** [comment]
Yet I find this problem in my server too. : (

**Comment by 3944Realms** [comment]
![image](https://github.com/user-attachments/assets/0a484aa6-142b-4378-8402-db29fe980b01)
不好评价

**Comment by 3944Realms** [comment]
申请线程复用率是否有点太低

**Comment by cnlimiter** [comment]
已修复 请使用1.18.2 1.0.0版本
