### ISSUE TITLE
[Bug/漏洞] 服务器无法正常关闭

### ISSUE THREAD

**Issue by BedrockEgg** [Nova-Committee/Atom-Sweep#17]
### Checks / 检查

- [X] I confirm that I have [searched for existing issues / pull requests](https://github.com/cnlimiter/Atom-Sweep/issues?q=) before reporting to avoid duplicate reporting./我确认在报告之前我已经搜索了[现有的问题或者拉取请求](https://github.com/cnlimiter/McBot/issues?q=)，以避免重复报告。
- [X] I confirm that I followed the Docs and read the [Changelog](https://github.com/cnlimiter/Atom-Sweep/releases/latest), but this problem still exists./我确认我按照文档配置并阅读了[Changelog](https://github.com/cnlimiter/McBot/releases/latest)，但这个问题仍然存在。
- [X] I confirm that I noted that if I don't follow the instructions, the issue may be closed directly./我确认我已经检查，如果我不按照说明进行操作，该问题可能会被直接关闭。

### Java Version / Java版本

21.0.4

### Minecraft Version / Minecraft版本

1.20.1

### McBot Version / Atom-Sweep版本

0.2.2.

### Description / 描述

加入mod后服务器无法正常关闭,卸载后恢复正常
![IMG_20240925_191848](https://github.com/user-attachments/assets/f78fee01-f307-4843-9a7c-2e708a3659e8)

### To Reproduce / 重现

安装mod后

### Log / 日志

[latest.log](https://github.com/user-attachments/files/17130014/latest.log)

**Comment by cnlimiter** [comment]
已更新 1.20.1 1.0.0版本
