### ISSUE TITLE
[1.19.2] 与Kubejs一起安装导致服务器无法运行

### ISSUE THREAD

**Issue by Dr-WeiAL** [Nova-Committee/Atom-Sweep#4]
[latest.log](https://github.com/Nova-Committee/Atom-Sweep/files/11776491/latest.log)
[crash-2023-06-17_06.16.14-server.txt](https://github.com/Nova-Committee/Atom-Sweep/files/11776492/crash-2023-06-17_06.16.14-server.txt)
启动完之后就崩溃关服了

**Comment by cnlimiter** [comment]
已修复
