### ISSUE TITLE
配置项中sweepPeriod的单位不明确

### ISSUE THREAD

**Issue by SherkeyXD** [Nova-Committee/Atom-Sweep#6]
sweepNotify我能猜出来是提前多少秒进行通知，sweepDiscount也能看出来是倒计时
但是sweepPeriod的单位是什么（

**Comment by yhzcake** [comment]
单位是分钟,每过几分钟进行一次实体清理

**Comment by cnlimiter** [comment]
清理周期，按分钟计算
